### ISSUE TITLE
Completely burned out buildings still exist in the menu

### ISSUE THREAD

**Issue by MemoryPenguin** [MemoryPenguin/Survival-303-Issues#11]
Attempting to retool them results in 'no building selected'.

**Comment by Chiefwaffles** [comment]
Chao says that someone reported to him that the menu completely breaks if someone's building is completely burned down and they respawn.

**Comment by MemoryPenguin** [comment]
Fixed issue reported in original post; other issue does not appear to be present anymore. Fix will be pushed in 6.27.
