### ISSUE TITLE
Fire can be foraged

### ISSUE THREAD

**Issue by Scarfacial** [MemoryPenguin/Survival-303-Issues#21]
With the new restrictions on the Drag tool, parts which are on fire should be made unforagable with the Forage tool. This would prevent people from foraging burning parts and dropping them into bases making it very difficult for the base owner/s to deal with.

**Comment by KingKobraX2** [comment]
This is true.
What is also true, I like to carry a burning bush around in case I need to cook something.

**Comment by Scarfacial** [comment]
Fixed in previous patch
