### ISSUE TITLE
Seat teleportation

### ISSUE THREAD

**Issue by Qoazi** [MemoryPenguin/Survival-303-Issues#24]
I'm sure atleast some of you Reading now, But teleporting is (once again) possible with seats, Just drag a seat, Sit on it without releasing your grab and then drag it away, When you release the mouse you'll be teleported to wherever you dragged the seat

**Comment by MemoryPenguin** [comment]
It's worth noting that while this was fixed in dev I do not believe that change was ever pushed to production.
