### ISSUE TITLE
Fireproofed objects still dealing damage

### ISSUE THREAD

**Issue by Qoazi** [MemoryPenguin/Survival-303-Issues#25]
Objects put on fire, And then fireproofed tend to still deal damage when touched, I've been unable to repeat this (but tried for maybe 15 minutes)

Another is that the ground caught on fire, Or atleast dealt damage like it was but didn't look like it was burning nor spread fire.  I ended up deleting the brick though (The top brick on Bento).

**Comment by Qoazi** [comment]
Apparently this happens when a fireproofed object is lit on fire, Or the ground, Or any object....

**Comment by MemoryPenguin** [comment]
I can't reproduce this in the testing grounds; the fire script doesn't seem to be functional? Objects are having `FireScript` cloned into them but water containers cannot extinguish it and the objects don't have a visual change (beyond the fact that they cannot be foraged). @Scarfacial could you take a look at this?
