### ISSUE TITLE
Minor Armour Bug

### ISSUE THREAD

**Issue by Qoazi** [MemoryPenguin/Survival-303-Issues#26]
Minor bug, Like really minor, Was contemplating wether or not to ever even bring it up but why not.
The bug is that sometimes armour is unequippable, This happens after it is placed from the backpack.
it is solved by simply foraging and replacing. 
Video:

https://youtu.be/rwYUGCDd_H8

**Comment by Scarfacial** [comment]
Fixed in patch 6.26
