### ISSUE TITLE
Dragseating

### ISSUE THREAD

**Issue by Scarfacial** [MemoryPenguin/Survival-303-Issues#27]
Due to a critical bug in Roblox's engine, Dragseating is currently possible and somewhat un-patchable. Changing the Humanoid.Sit property has no effect upon Humanoid physics (therefore seating people into terrain is possible) and the Seat.Disabled property does not replicate.

**Comment by MemoryPenguin** [comment]
Wonderful. Is there anything we can actually do about it (reasonably) or are we stuck waiting?

**Comment by Scarfacial** [comment]
I'm not sure, it will need investigating.

**Comment by MemoryPenguin** [comment]
Theoretical workaround applied in dev; needs testing - seats can only be rotated on one axis.

**Comment by MemoryPenguin** [comment]
New patch applied; players will be moved upwards when seated into the terrain. If a player is seated into the terrain twice within 1 minute by the same seat, it will be removed. So far this has been successful in testing. The earlier workaround has been removed; seats are no longer constrained to a single axis of rotation.

**Comment by Scarfacial** [comment]
This will be abused to climb mountains etc. Acceptable only as a very temporary fix.

**Comment by MemoryPenguin** [comment]
Patch patched; shipping with 6.27.
