### ISSUE TITLE
Massive code duplication in tools

### ISSUE THREAD

**Issue by MemoryPenguin** [MemoryPenguin/Survival-303-Issues#28]
At the moment the way 303 tools are set up is you pick a similar tool, copy the script, and play with its values. This makes changing the behavior of tools rather difficult. The easiest way to do this is probably to create a module for each tool class and have a stub script in the tool itself that sets the configuration values.

Progress
=======
- [x] BaseTool
- [x] Tool classes
  - [x] MeleeWeapon
    - [x] HarvestingTool
      - [x] PickaxeTool
      - [x] AxeTool (encompasses hatchets as well)
    - [x] KnifeTool
    - [x] FarmingTool
    - [x] JavelinTool
  - [x] RangedWeapon
  - [x] WaterContainerTool
  - [x] FishingTool
  - [x] FirestartingTool
  - [x] PaintingTool
  - [x] OilFilteringTool
  - [x] LightSourceTool
  - [x] LadleTool
  - [x] MilkingTool
  - [x] CheeseTool
- [x] User interface framework
  - [x] ToolUI
  - [x] Fragment
  - [x] CooldownFragment
  - [x] BaseTool uses ToolUI class instead of hardcoded UI
- [x] actual user interface framework and not whatever i made above

API
===
Module example:
```lua
local ExampleTool = {}
ExampleTool.__index = ExampleTool

function ExampleTool.new(toolObject)
	local self = setmetatable({}, ExampleTool)
	self.Object = toolObject

	toolObject.Equipped:connect(function(mouse)
		mouse.Button1Down:connect(function()
			self:OnActivated(mouse.Hit.p, mouse.Target)
		end)
	end)

	-- set default config values here
	self.Range = 10
	return self
end

function ExampleTool:OnActivated(position, target)
	if (self.Object.Handle.CFrame.p - position).magnitude <= self.Range
		and target then

		print(target.Name)
	end
end

return ExampleTool
```

And a tool example:
```lua
local ToolClass = require(game.ReplicatedStorage.Code.ToolClasses.Example)
local Object = ToolClass.new(script.Parent)
Object.Range = 25
```

So there we go. To further reduce tool duplication I might look into having a base 'ToolClass' class that handles setup (delegating events, few other things). That would make a module look something like this:
```lua
local BaseClass = require(script.Parent.ToolBase)
local ExampleTool = {}
ExampleTool.__index = ExampleTool
setmetatable(ExampleTool, BaseClass)

function ExampleTool.new(toolObject)
	local self = setmetatable(BaseClass.new(toolObject), ExampleTool)
	-- note the lack of an event connector
	self.Range = 10
	return self
end

function ExampleTool:OnActivated(position, target)
	if (self.Object.Handle.CFrame.p - position).magnitude <= self.Range
		and target then

		print(target.Name)
	end
end

return ExampleTool
```

The tools would remain the same. If I did this, these methods would be available for event handling:

`OnActivated(Vector3 position, BasePart target)`
--------------------------------------------------------------
Effectively mouse.Button1Down. position is mouse.Hit.p, target is the mouse's target, if any.

`OnEquipped()`
--------------------------------------------------------------
Called when the tool is equipped. This does *not* pass a mouse object and should be used to load values from the tool object itself (when it was taken before being equipped).

`OnUnequipped()`
--------------------------------------------------------------
Called when the tool is unequipped. This should be used to save values in the tool's memory - e.g. for a water container, saving the current amount of water. This is important in order to make sure that data is stored when the tool is stored via the `/store` command.

**Comment by Scarfacial** [comment]
This is something I've wanted to happen for a long time, but I only once attempted to make it and got lazy before fixing the bugs that came with due to the way I wrote it. I 100% support this idea.

**Comment by MemoryPenguin** [comment]
So, quick progress update: this is still happening; dev is currently **unstable** until this is completed. Some tool mechanics have changed slightly; I'll write up a full changelog on this later. Most of the boilerplate is complete; I 'just' have to rewrite the rest of 303's various tool types and set them up, which is mostly a lot of repetitive user interface work that's *just* unique enough that it can't be easily automated. Earliest completion date is probably this weekend.

**Comment by MemoryPenguin** [comment]
Another progress update: This is, in fact, still in progress - I got sucked into Starbound and barely escaped drowning in schoolwork. Things are coming, but feedback's welcome - see the [dev server](http://www.roblox.com/games/64468343/Survival-303-Development-Server). Still things to get done.

**Comment by MemoryPenguin** [comment]
So. Really sorry for just vanishing on this - I got caught up in a bunch of stuff and now finals are on top of me, so I simply don't have time to work on this right now. **With that said** I'm going to try to get this done before the end of the year - no promises. The few tools that remain are the more difficult ones to write; you'll probably see them in this order:

1. PaintingTool (paintbrushes)
2. LadleTool
3. RangedWeapon (crossbows, etc.)
4. FarmingTool (sickles)
5. FishingTool (fishing rods, nets, etc.)

After that you probably won't see a whole lot immediately. I've started to work on [a new game](http://www.roblox.com/games/320954825/Cold-Shores), and if some of the stuff there works out I may look into integrating it into 303. However, school is still my top priority, so...we'll see.

**Comment by MemoryPenguin** [comment]
More stuff. Tests are done; I am officially on Christmas Break. Work resuming sometime tonight.

**Comment by Scarfacial** [comment]
When will this be ready to ship to production?

**Comment by MemoryPenguin** [comment]
Aiming for next Wednesday, ideally sooner.

**Comment by MemoryPenguin** [comment]
Tasks complete; testing required.

**Comment by MemoryPenguin** [comment]
Tests complete; dev complete.
