### ISSUE TITLE
Quarries occasionally break

### ISSUE THREAD

**Issue by MemoryPenguin** [MemoryPenguin/Survival-303-Issues#30]
Sometimes a quarry will simply break; the button will be green but pressing it does not result in a boulder being created.

**Comment by Qoazi** [comment]
This Always occur if you do not forage/Craft with the Boulder, is this what are referring to or is there a bug too?  because that seemed an intended function

**Comment by MemoryPenguin** [comment]
Nope; tested it myself - quarries remained broken even after removing the product.

**Comment by MemoryPenguin** [comment]
Theoretically fixed in 6.27, we'll see.
