### ISSUE TITLE
Crippling, frequent lagspikes

### ISSUE THREAD

**Issue by MemoryPenguin** [MemoryPenguin/Survival-303-Issues#5]
This is, as far as we can tell, a ROBLOX issue that is caused by something in 303.  We're trying to find the cause of it so we can produce reproduction steps, but that will take time.

**Comment by Scarfacial** [comment]
As a note, this is an ongoing issue and has been around since long before the recent updates. The recent updates to chat have made it more proclaimed since it's running on our own custom system now, rather than the Roblox default.

**Comment by MemoryPenguin** [comment]
What do we know about the circumstances of this so far?  Does it occur on the client, the server, or both?  Did it begin to occur before the chat update or afterwards?  I haven't actually seen it (though I suspect part of that is the output viewer breaking), so I don't know anything about it other than it occurs and it's a ROBLOX issue.

**Comment by Scarfacial** [comment]
I have observed no client lag,  so it appears to be either entirely on the server or in networking issues. Root cause and contributing factors unknown.

**Comment by KingKobraX2** [comment]
From my personal experience, I always get the client lag every time I join a server. The lag for me affects things like chat delay and freezing players. As an additional note; I've been in servers where some people don't experience this lag at all, but others do. Not sure what's happening, this is just my findings.

**Comment by MemoryPenguin** [comment]
Some more information: Lag appears to occur when players join.  Potentially unrelated, but potentially not: under some (unknown) circumstances, FilterStringForPlayerAsync errors with a WinHTTP error code of 0x2EE2.  This number is 12002 in decimal format, [which corresponds to the error ERROR_WINHTTP_TIMEOUT](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383770%28v=vs.85%29.aspx).

**Comment by MemoryPenguin** [comment]
My current theory is that the server is undergoing extreme network lag.  Cause unknown.

**Comment by Scarfacial** [comment]
I am in contact with the engineers about this issue.

**Comment by MemoryPenguin** [comment]
ROBLOX appears to have patched this.

**Comment by Scarfacial** [comment]
I've just confirmed this is still happening to some players.

**Comment by MemoryPenguin** [comment]
Is this still the same error (accompanied by 'cache update failed'  info messages in the server-sided output)?

**Comment by Scarfacial** [comment]
The 'cache update failed' issue is still in place, however it is not the main cause of this. The exact cause is still unknown, but it is believed to be an issue with RemoteEvents/Functions. If we can somehow find a repro, it would help solve the issue permanently.
