### ISSUE TITLE
Save system is glitchy

### ISSUE THREAD

**Issue by MemoryPenguin** [MemoryPenguin/Survival-303-Issues#9]
The save system is glitchy.  This is responsible for the behaviors described in #7 and #8.  Ideally it needs to be reworked completely.

**Comment by Chiefwaffles** [comment]
How is this related to #8? I can see saving being responsible for a broken forage tool (saving forage tool), but how swimming?

Also, maybe don't close issues in this issue? Reference them and maybe add the duplicate label, sure, but it feels like they should still be open.

**Comment by Scarfacial** [comment]
#8 is caused by skills failing to initialize, and the swim script yields indefinitely waiting for the swimming skill to be found.

**Comment by MemoryPenguin** [comment]
Closed, save system is disabled.  See #12.
